/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ACER 53F4
 */
public class Home extends javax.swing.JFrame{
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        switchReactor1.setOnOff(false);
        switchReactor2.setOnOff(false);
        switchReactor3.setOnOff(false);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();
        switchReactor1 = new gui.Switch();
        jLabelEstado1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        switchReactor2 = new gui.Switch();
        jLabelEstado2 = new javax.swing.JLabel();
        switchReactor3 = new gui.Switch();
        jLabelEstado3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSlider1.setMajorTickSpacing(15);
        jSlider1.setMaximum(150);
        jSlider1.setMinorTickSpacing(1);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 413, -1));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reactorpequeño.png"))); // NOI18N
        jLabel1.setText("Reactor 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reactor2.png"))); // NOI18N
        jLabel2.setText("Reactor 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jSlider2.setMajorTickSpacing(15);
        jSlider2.setMaximum(150);
        jSlider2.setMinorTickSpacing(1);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);
        getContentPane().add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 413, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reactor3.png"))); // NOI18N
        jLabel3.setText("Reactor 3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        jSlider3.setMajorTickSpacing(15);
        jSlider3.setMaximum(150);
        jSlider3.setMinorTickSpacing(1);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setSnapToTicks(true);
        getContentPane().add(jSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 413, -1));

        switchReactor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchReactor1MouseClicked(evt);
            }
        });
        getContentPane().add(switchReactor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 90, 50));

        jLabelEstado1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelEstado1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado1.setText("APAGADO");
        getContentPane().add(jLabelEstado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reparar.png"))); // NOI18N
        jButton1.setText("REPARAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 110, 140, 44));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reparar.png"))); // NOI18N
        jButton2.setText("REPARAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 130, 40));

        switchReactor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchReactor2MouseClicked(evt);
            }
        });
        getContentPane().add(switchReactor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 90, 50));

        jLabelEstado2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelEstado2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado2.setText("APAGADO");
        getContentPane().add(jLabelEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        switchReactor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchReactor3MouseClicked(evt);
            }
        });
        getContentPane().add(switchReactor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 90, 50));

        jLabelEstado3.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabelEstado3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEstado3.setText("APAGADO");
        getContentPane().add(jLabelEstado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reparar.png"))); // NOI18N
        jButton4.setText("REPARAR");
        jButton4.setPreferredSize(new java.awt.Dimension(127, 43));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 490, 130, 44));

        btnSalir.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nose.jpg"))); // NOI18N
        btnSalir.setText("Salir");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 190, 90));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 780, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 182, 770, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 780, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondoplanta.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void switchReactor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchReactor1MouseClicked
        if(!switchReactor1.isOnOff()){
            jLabelEstado1.setText("APAGADO");
        }else{
            jLabelEstado1.setText("ENCENDIDO");
        }
    }//GEN-LAST:event_switchReactor1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void switchReactor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchReactor2MouseClicked
        if(!switchReactor2.isOnOff()){
            jLabelEstado2.setText("APAGADO");
        }else{
            jLabelEstado2.setText("ENCENDIDO");
        }
    }//GEN-LAST:event_switchReactor2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void switchReactor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchReactor3MouseClicked
        if(!switchReactor3.isOnOff()){
            jLabelEstado3.setText("APAGADO");
        }else{
            jLabelEstado3.setText("ENCENDIDO");
        }
    }//GEN-LAST:event_switchReactor3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged
        System.out.println("me estas arrastrando");
    }//GEN-LAST:event_jSlider1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelEstado1;
    private javax.swing.JLabel jLabelEstado2;
    private javax.swing.JLabel jLabelEstado3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private gui.Switch switchReactor1;
    private gui.Switch switchReactor2;
    private gui.Switch switchReactor3;
    // End of variables declaration//GEN-END:variables

}
